name: Deploy to Prod Environment
display_name: Deploy to Prod Environment

   on:
     push:
       branches:
         - main
       paths:
         - 'prod/**'
         - '.github/workflows/prod-deploy.yml'

   jobs:
     deploy:
       runs-on: ubuntu-latest
       steps:
         - name: Checkout code
           uses: actions/checkout@v3

         - name: Setup Terraform
           uses: hashicorp/setup-terraform@v2
           with:
             terraform_version: 1.5.0

         - name: Terraform Init
           run: terraform init
           working-directory: prod

         - name: Terraform Validate
           run: terraform validate
           working-directory: prod

         - name: Terraform Plan
           run: terraform plan -out=tfplan
           working-directory: prod
           env:
             ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
             ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
             ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
             ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
             ARM_REGION: ${{ secrets.ARM_REGION }}

         - name: Terraform Apply
           run: terraform apply -auto-approve tfplan
           working-directory: prod
           env:
             ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
             ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
             ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
             ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
             ARM_REGION: ${{ secrets.ARM_REGION }}