name: Terraform Deploy (Manual)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
      region:
        description: 'Target region'
        required: true
        default: 'eastus'
        type: choice
        options:
          - eastus
          - westus2

jobs:
  terraform:
    name: 'Terraform - ${{ github.event.inputs.region }} / ${{ github.event.inputs.environment }}'
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    defaults:
      run:
        shell: bash
        working-directory: app/stacks/${{ github.event.inputs.region }}/${{ github.event.inputs.environment }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Terraform Init
      run: |
        terraform init -backend-config="key=${{ github.event.inputs.region }}-${{ github.event.inputs.environment }}.tfstate"

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -var-file="${{ github.event.inputs.environment }}.tfvars"

    - name: Terraform Apply
      if: github.event.inputs.environment == 'dev' || github.event.inputs.environment == 'prod'
      run: terraform apply -auto-approve -var-file="${{ github.event.inputs.environment }}.tfvars"
